#! /bin/bash

# Prerequisites:
# - Build the design to create the SOF
# - Compile the hps_debug application and create the SOF with the hps_debug application included
# - Initialize your .gitconfig file

# Command line parameters:
# - RBF_FILE: Path to the RBF file generated by the design build (default is empty, must be set)
# - BOOT_SOURCE: Boot source for the build, either 'sd' or 'qspi' (default is empty, must be set)

# Supported environment variables:
# - GITCONFIG_CREATE_SCRIPT: Path to a script that creates the .gitconfig file
# - GITCONFIG_CREATE_SCRIPT_PARAMS: Parameters to pass to the gitconfig creation script
# - CONTAINER_COMMAND: Command to run the build in a container (e.g., "docker run --rm -v $(pwd):/workspace -w /workspace your_container_image")

set -e

RBF_FILE=$1
BOOT_SOURCE=$2
GITCONFIG_CREATE_SCRIPT=${GITCONFIG_CREATE_SCRIPT:-""}
CONTAINER_COMMAND=${CONTAINER_COMMAND:-""}

echo "Yocto Linux Build Script"
echo "RBF File: $RBF_FILE"
echo "Gitconfig Creation Script: $GITCONFIG_CREATE_SCRIPT"
echo "Container Command: $CONTAINER_COMMAND"

if [ ! -f "$RBF_FILE" ]; then
    echo "Error: RBF file not found at $RBF_FILE"
    echo "Please build the design first to generate the RBF file."
    exit 1
fi

if [ "$BOOT_SOURCE" != "sd" ] && [ "$BOOT_SOURCE" != "qspi" ] && [ "$BOOT_SOURCE" != "emmc" ] && [ "$BOOT_SOURCE" != "nand" ]; then
    echo "Error: Boot source must be 'sd', 'qspi', 'emmc', or 'nand'"
    echo "Usage: $0 <RBF_FILE> <BOOT_SOURCE>"
    echo "  BOOT_SOURCE: 'sd', 'qspi', 'emmc', or 'nand'"
    exit 1
fi

# Check if the gitconfig creation script is provided
if [ -n "$GITCONFIG_CREATE_SCRIPT" ]; then
    if [ ! -f "$GITCONFIG_CREATE_SCRIPT" ]; then
        echo "Error: Gitconfig creation script not found at $GITCONFIG_CREATE_SCRIPT"
        exit 1
    else
        echo "Running gitconfig creation script: $GITCONFIG_CREATE_SCRIPT"
        bash "$GITCONFIG_CREATE_SCRIPT"

        if [ $? -ne 0 ]; then
            echo "Error: Gitconfig creation script failed."
            exit 1
        fi
    fi
else
    echo "Warning: No gitconfig creation script provided. Skipping gitconfig setup."
fi

# If .gitconfig file exists in the current directory set the GITCONFIG_FILE environment variable
if [ -f "./.gitconfig" ]; then
    export GITCONFIG_FILE="./.gitconfig"
    echo "Using .gitconfig file from current directory."
else
    echo "Warning: No .gitconfig file found in the current directory."
    echo "Please ensure your .gitconfig is set up correctly."
fi

if [ -z "$CONTAINER_COMMAND" ]; then
    bash ./kas_build.sh $RBF_FILE $BOOT_SOURCE
    if [ $? -ne 0 ]; then
        echo "Error: Build command failed."
        exit 1
    fi
else
    echo "Executing container command: $CONTAINER_COMMAND ./kas_build.sh $RBF_FILE"
    $CONTAINER_COMMAND ./kas_build.sh $RBF_FILE $BOOT_SOURCE
    if [ $? -ne 0 ]; then
        echo "Error: Container command failed."
        exit 1
    fi
fi

echo "Build completed successfully."
